//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_Kutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int kitapID { get; set; }
        public string kitapAdi { get; set; }
        public string kitapYazari { get; set; }
        public string kitapTuru { get; set; }
        public string yayinEvi { get; set; }
        public Nullable<int> rafNumara { get; set; }
    }
}
