//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_Kutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        public int uyeID { get; set; }
        public Nullable<int> uyeTC { get; set; }
        public string uyeADİ { get; set; }
        public string uyeSOYADİ { get; set; }
        public Nullable<int> uyeTELNO { get; set; }
        public string uyeMAİL { get; set; }
    }
}
